export const noticeTypesEnum = t => [
  {value: 0, label: t('noticeType.all')},
  {value: 1, label: t('noticeType.offerAccommodation')},
  {value: 10, label: t('noticeType.searchAccommodation')},
  {value: 20, label: t('noticeType.offerTransportHelp')},
  {value: 22, label: t('noticeType.searchTransportHelp')},
  {value: 30, label: t('noticeType.offerTranslationHelp')},
  {value: 32, label: t('noticeType.searchTranslationHelp')},
  {value: 50, label: t('noticeType.offerHelp')},
  {value: 52, label: t('noticeType.searchHelp')},
  {value: 60, label: t('noticeType.offerHelpForAnimal')},
  {value: 62, label: t('noticeType.searchHelpForAnimal')},
  {value: 70, label: t('noticeType.offerMedicalHelp')},
  {value: 72, label: t('noticeType.searchMedicalHelp')}, 
  {value: 80, label: t('noticeType.offerLegalAssistance')},
  {value: 82, label: t('noticeType.searchLegalAssistance')},
  {value: 90, label: t('noticeType.offerPsychologicalHelp')},
  {value: 92, label: t('noticeType.searchPsychologicalHelp')},
  {value: 100, label: t('noticeType.offerVolunteerHelp')},
  {value: 102, label: t('noticeType.searchVolunteerHelp')},
  {value: 110, label: t('noticeType.offeringWork')},
  {value: 112, label: t('noticeType.searchWork')},
]