export const voivodeshipsEnum = mt =>[
  { value: 1, label: mt('dolnośląskie') },
  { value: 2, label: mt('kujawsko-pomorskie') },
  { value: 3, label: mt('lubelskie') },
  { value: 4, label: mt('lubuskie') },
  { value: 5, label: mt('łódzkie') },
  { value: 6, label: mt('małopolskie') },
  { value: 7, label: mt('mazowieckie') },
  { value: 8, label: mt('opolskie') },
  { value: 9, label: mt('podkarpackie') },
  { value: 10, label: mt('podlaskie') },
  { value: 11, label: mt('pomorskie') },
  { value: 12, label: mt('śląskie') },
  { value: 13, label: mt('świętokrzyskie') },
  { value: 14, label: mt('warmińsko-mazurskie') },
  { value: 15, label: mt('wielkopolskie') },
  { value: 16, label: mt('zachodniopomorskie') },
]