export const PERMISSION_USER = 'User'
export const PERMISSION_ADMIN = 'Admin'
export const PERMISSION_CITY_ADMIN = 'CityAdmin'
export const PERMISSION_ALL = [PERMISSION_ADMIN, PERMISSION_USER, PERMISSION_CITY_ADMIN]
